$ANSIBLE_VAULT;1.1;AES256
38363262616562383862333366323861626236656131316138663033316230353730323536336439
6133306133376435313138666538636662366364633231610a353736386463366432663036656162
35396164613031323364316134313338333738373737626635323464633062663633313933373035
6462353038616534660a323133343735323761396632633762373765376336326364636365393437
39663336643961333639383164313262616135613831326131393238356130343538373135323432
38663434383466386233353365343835343739626664353339653039383365656636303861396539
30613765373366363239386539633665313661623635323430623161356565336431393963636238
64383364653235613333653833363264303261393666613531396235366230356239656633383930
34613862626134376233313031613563643931346132373466316339626164333639623163313437
39306666656165346630353132353833366230646265393266656535386532346334643230643138
65643838323261623136353332636431366565323638356262666265383333373436346338363037
62326137316665636635
